// Bake produces fully-inlined island HTML at generation time: resolved CDN
// dep tags are replaced by their vendored content (CSS as <style>, JS as the
// original <script> tag minus src), duplicate URLs within a file appear once,
// and unresolved tags ship verbatim. The render path stays a plain
// prefix+blob+suffix splice against the baked bytes.
package codegen

import (
	"bytes"
	"fmt"

	"github.com/fritzkeyzer/islandc/internal/island"
)

// Baked is the result of inlining resolved deps into one island's HTML.
type Baked struct {
	HTML []byte
	// DataOpen and DataClose are the data island body bounds within HTML,
	// shifted to account for the inlined content.
	DataOpen, DataClose int
}

// bakedHeader marks baked files as generated.
const bakedHeader = "<!-- Code generated by islandc; CDN deps inlined. DO NOT EDIT (edit the .island.html source). -->\n"

// Bake inlines every resolved dep of f into its HTML. read loads a vendored
// file's content by its cache filename. JS content containing "</script>"
// cannot be inlined safely; such deps ship verbatim and a warning is
// returned. If f has no resolved deps, Bake returns (nil, warnings, nil)
// and the source HTML should be embedded as-is.
func Bake(f *island.File, resolved map[string]string, read func(name string) ([]byte, error)) (*Baked, []string, error) {
	var out bytes.Buffer
	out.WriteString(bakedHeader)
	var warnings []string
	inlined := map[string]bool{}
	spliced := false
	cursor := 0
	dataOpen, dataClose := f.DataOpen+len(bakedHeader), f.DataClose+len(bakedHeader)

	// Deps are in document order and never overlap the data island body.
	for _, d := range f.Deps {
		filename, ok := resolved[d.URL]
		if !ok {
			continue
		}
		var replacement []byte
		if !inlined[d.URL] {
			content, err := read(filename)
			if err != nil {
				return nil, warnings, fmt.Errorf("bake %s: read vendored dep %s: %w", f.Path, filename, err)
			}
			switch d.Kind {
			case island.DepCSS:
				replacement = append(append([]byte("<style>"), content...), "</style>"...)
			case island.DepJS:
				if bytes.Contains(content, []byte("</script>")) {
					warnings = append(warnings, fmt.Sprintf("%s: dep %s contains \"</script>\" and cannot be inlined; it will ship verbatim", f.Path, d.URL))
					continue
				}
				replacement = append(append([]byte(d.ScriptOpenTag), content...), "</script>"...)
			}
			inlined[d.URL] = true
		}
		// Duplicate occurrences get an empty replacement: tag removed.
		out.Write(f.HTML[cursor:d.TagStart])
		out.Write(replacement)
		shift := len(replacement) - (d.TagEnd - d.TagStart)
		if d.TagEnd <= f.DataOpen {
			dataOpen += shift
			dataClose += shift
		}
		cursor = d.TagEnd
		spliced = true
	}
	if !spliced {
		return nil, warnings, nil
	}
	out.Write(f.HTML[cursor:])
	return &Baked{HTML: out.Bytes(), DataOpen: dataOpen, DataClose: dataClose}, warnings, nil
}
