// Package codegen emits self-contained Go files from parsed island files.
//
// For each target directory, the generator emits a single .go file containing:
//
//   - one typed Data struct per island (inferred from the JSON Schema)
//   - the source HTML embedded via //go:embed per island (the .island.html
//     source files must remain alongside the generated file)
//   - one Render<Name>(w io.Writer, d <Name>Data) error function per island
//   - the injectIsland runtime helper (written once per generated file)
//
// The generated file has no dependency on this package or any islandc runtime;
// it imports only the standard library.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/fritzkeyzer/islandc/internal/island"
)

// Config controls a single generation pass over one directory.
type Config struct {
	// PackageName is the Go package name written into the generated file.
	// Defaults to the directory's base name.
	PackageName string
	// Files are the parsed island files to emit. All must target the same
	// directory; the caller is responsible for grouping them.
	Files []*island.File
}

// Generate returns the formatted Go source for one directory's islands.
func Generate(cfg Config) ([]byte, error) {
	if len(cfg.Files) == 0 {
		return nil, fmt.Errorf("codegen: no files")
	}
	pkg := cfg.PackageName
	if pkg == "" {
		pkg = "views"
	}

	// Stable order so output is reproducible across runs.
	files := append([]*island.File(nil), cfg.Files...)
	sort.SliceStable(files, func(i, j int) bool {
		return files[i].Name < files[j].Name
	})

	var b bytes.Buffer
	b.WriteString("// Code generated by islandc. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Source: .island.html files in this directory. See https://github.com/fritzkeyzer/islandc for the format.\n")
	b.WriteString("//\n")
	b.WriteString("// Each Render<Name> function writes the source HTML verbatim with the\n")
	b.WriteString("// island-data placeholder JSON replaced by json.Marshal(data).\n\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t_ \"embed\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString(")\n\n")

	// Track emitted struct names to detect collisions.
	seen := map[string]bool{}

	for _, f := range files {
		if err := emitIsland(&b, f, seen); err != nil {
			return nil, fmt.Errorf("codegen %s: %w", f.Path, err)
		}
	}

	emitInjector(&b)

	// gofmt the result for stable, idiomatic formatting.
	out, err := format.Source(b.Bytes())
	if err != nil {
		// Return the unformatted source to aid debugging.
		return b.Bytes(), fmt.Errorf("codegen: gofmt failed: %w", err)
	}
	return out, nil
}

func emitIsland(b *bytes.Buffer, f *island.File, seen map[string]bool) error {
	dataName := f.Name + "Data"
	if seen[dataName] {
		return fmt.Errorf("duplicate generated type %q (from %s)", dataName, f.Path)
	}
	// emitStruct registers dataName in seen.

	// Emit the Data struct tree.
	if err := emitStruct(b, dataName, f.Schema, seen, f.Name); err != nil {
		return err
	}

	// Emit the embedded HTML bytes. The source .island.html file is embedded
	// via //go:embed at compile time; it must remain in the same directory as
	// the generated file. injectIsland splices the marshaled data into the
	// island-data slot at serve time using offsets computed during parsing.
	htmlVar := unexportName(f.Name) + "HTML"
	fmt.Fprintf(b, "// %s is the source file verbatim, including the placeholder\n", htmlVar)
	fmt.Fprintf(b, "// JSON inside the island-data slot. injectIsland overwrites that\n")
	fmt.Fprintf(b, "// placeholder at serve time.\n")
	fmt.Fprintf(b, "//go:embed %s\n", f.Path)
	fmt.Fprintf(b, "var %s []byte\n\n", htmlVar)

	// Emit the Render function. The injector uses the byte offsets computed
	// at parse time so it never re-scans the HTML at runtime.
	fmt.Fprintf(b, "// %s writes the %s island HTML to w with the island-data\n", f.RenderFunc, f.Name)
	fmt.Fprintf(b, "// placeholder replaced by the marshaled form of d.\n")
	fmt.Fprintf(b, "func %s(w io.Writer, d %s) error {\n", f.RenderFunc, dataName)
	fmt.Fprintf(b, "\tblob, err := json.Marshal(d)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\treturn injectIsland(w, %s, blob, %d, %d)\n", htmlVar, f.DataOpen, f.DataClose)
	fmt.Fprintf(b, "}\n\n")
	return nil
}

// emitStruct writes a Go struct for the given schema node. Nested object
// schemas become nested structs named <Parent><FieldName>, emitted after
// the parent struct (so they never appear inline between fields).
func emitStruct(b *bytes.Buffer, name string, schema *island.Schema, seen map[string]bool, islandName string) error {
	if schema == nil || schema.Type != "object" || len(schema.Properties) == 0 {
		return fmt.Errorf("cannot emit struct %q: schema is not a non-empty object", name)
	}
	if seen[name] {
		return fmt.Errorf("duplicate generated type %q (in island %s)", name, islandName)
	}
	seen[name] = true

	fmt.Fprintf(b, "type %s struct {\n", name)
	// Stable field order: sort by property name.
	keys := make([]string, 0, len(schema.Properties))
	for k := range schema.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var pending bytes.Buffer // nested struct definitions, emitted after the parent
	for _, key := range keys {
		sub := schema.Properties[key]
		fieldName := exportName(key)
		goType, err := goType(&pending, name, fieldName, sub, seen, islandName)
		if err != nil {
			return err
		}
		jsonTag := key
		if sub != nil && sub.Tag != "" {
			jsonTag = sub.Tag
		}
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", fieldName, goType, jsonTag)
	}
	fmt.Fprintf(b, "}\n\n")

	// Append any nested struct definitions generated while walking fields.
	b.Write(pending.Bytes())
	return nil
}

// goType returns the Go type for a schema node, emitting nested structs as
// needed. parentName and fieldName are used to name nested struct types.
func goType(b *bytes.Buffer, parentName, fieldName string, schema *island.Schema, seen map[string]bool, islandName string) (string, error) {
	if schema == nil {
		return "interface{}", nil
	}
	switch schema.Type {
	case "string":
		return "string", nil
	case "number":
		return "float64", nil
	case "integer":
		return "int", nil
	case "boolean":
		return "bool", nil
	case "array":
		if schema.Items == nil {
			return "[]interface{}", nil
		}
		elem, err := goType(b, parentName, fieldName, schema.Items, seen, islandName)
		if err != nil {
			return "", err
		}
		return "[]" + elem, nil
	case "object":
		nestedName := parentName + fieldName
		if err := emitStruct(b, nestedName, schema, seen, islandName); err != nil {
			return "", err
		}
		return nestedName, nil
	default:
		return "", fmt.Errorf("unsupported schema type %q in island %s", schema.Type, islandName)
	}
}

// emitInjector writes the runtime helper. It takes precomputed byte offsets
// so it does not scan the HTML at runtime — it just writes prefix, blob,
// suffix. This is the only runtime function in the generated file.
func emitInjector(b *bytes.Buffer) {
	b.WriteString("// injectIsland writes html to w with the bytes between\n")
	b.WriteString("// [openEnd, closeStart) replaced by blob. openEnd and closeStart\n")
	b.WriteString("// are the absolute byte offsets of the island-data slot's opening\n")
	b.WriteString("// tag end and closing tag start, computed at codegen time.\n")
	b.WriteString("func injectIsland(w io.Writer, html, blob []byte, openEnd, closeStart int) error {\n")
	b.WriteString("\tif openEnd < 0 || closeStart < 0 || openEnd > closeStart || closeStart > len(html) {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"islandc: invalid island-data splice bounds\")\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif _, err := w.Write(html[:openEnd]); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif _, err := w.Write(blob); err != nil {\n")
	b.WriteString("\t\treturn err\n")
	b.WriteString("\t}\n")
	b.WriteString("\t_, err := w.Write(html[closeStart:])\n")
	b.WriteString("\treturn err\n")
	b.WriteString("}\n")
}

// exportName capitalizes the first rune of s.
func exportName(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = []rune(strings.ToUpper(string(r[0])))[0]
	return string(r)
}

// unexportName lowercases the first rune of s.
func unexportName(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = []rune(strings.ToLower(string(r[0])))[0]
	return string(r)
}
