// Package codegen emits one self-contained Go file per directory from parsed
// island files. Per island: a typed Data struct, embedded HTML, a Render<Name>
// function, and the injectIsland helper. Generated code imports only the
// standard library.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/fritzkeyzer/islandc/internal/island"
)

// Config describes one directory's generation input.
type Config struct {
	PackageName string
	Files       []*island.File
	// Version is the islandc version written into the generated header.
	Version string
	// Baked maps an island's Path to its generation-time inlined HTML.
	// Islands present here embed their baked sibling file (Path with the
	// .html suffix replaced by .gen.html) instead of the source. May be nil.
	Baked map[string]*Baked
}

// BakedPath returns the sibling filename for an island's baked HTML:
// counter.island.html -> counter.island.gen.html.
func BakedPath(sourcePath string) string {
	return strings.TrimSuffix(sourcePath, ".html") + ".gen.html"
}

// Generate returns the formatted Go source for one directory's islands.
func Generate(cfg Config) ([]byte, error) {
	if cfg.PackageName == "" {
		return nil, fmt.Errorf("codegen: package name is required")
	}
	if len(cfg.Files) == 0 {
		return nil, fmt.Errorf("codegen: no island files given")
	}

	files := make([]*island.File, len(cfg.Files))
	copy(files, cfg.Files)
	sort.Slice(files, func(i, j int) bool { return files[i].Name < files[j].Name })

	version := cfg.Version
	if version == "" {
		version = "dev"
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by islandc (%s). DO NOT EDIT.\n\n", version)
	b.WriteString("package " + cfg.PackageName + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t_ \"embed\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString(")\n\n")

	seen := map[string]bool{}
	for _, f := range files {
		if err := emitIsland(&b, f, cfg.Baked[f.Path], seen); err != nil {
			return nil, fmt.Errorf("codegen %s: %w", f.Path, err)
		}
	}
	emitInjector(&b)

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: generated output does not gofmt: %w\n---\n%s", err, b.String())
	}
	return out, nil
}

func emitIsland(b *bytes.Buffer, f *island.File, baked *Baked, seen map[string]bool) error {
	dataName := f.Name + "Data"
	if seen[dataName] {
		return fmt.Errorf("duplicate generated type %q (from %s)", dataName, f.Path)
	}
	if err := emitStruct(b, dataName, f.Schema, seen, f.Name); err != nil {
		return err
	}

	// Embed the baked sibling when deps were inlined; otherwise the source.
	embedPath, open, close := f.Path, f.DataOpen, f.DataClose
	if baked != nil {
		embedPath, open, close = BakedPath(f.Path), baked.DataOpen, baked.DataClose
	}
	htmlVar := unexportName(f.Name) + "HTML"
	fmt.Fprintf(b, "//go:embed %s\n", embedPath)
	fmt.Fprintf(b, "var %s []byte\n\n", htmlVar)

	fmt.Fprintf(b, "// %s writes the %s island HTML with the data island body\n", f.RenderFunc, f.Name)
	fmt.Fprintf(b, "// replaced by json.Marshal(d).\n")
	fmt.Fprintf(b, "func %s(w io.Writer, d %s) error {\n", f.RenderFunc, dataName)
	fmt.Fprintf(b, "\tblob, err := json.Marshal(d)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\treturn injectIsland(w, %s, blob, %d, %d)\n", htmlVar, open, close)
	fmt.Fprintf(b, "}\n\n")
	return nil
}

// emitStruct writes a Go struct for the given schema node. Nested object
// schemas become nested structs named <Parent><FieldName>, emitted after the
// parent struct.
func emitStruct(b *bytes.Buffer, name string, schema *island.Schema, seen map[string]bool, islandName string) error {
	if schema.Type != "object" {
		return fmt.Errorf("struct %s: schema type is %q, want object", name, schema.Type)
	}
	if seen[name] {
		return fmt.Errorf("duplicate generated type %q", name)
	}
	seen[name] = true

	if schema.Comment != "" {
		fmt.Fprintf(b, "// %s %s\n", name, schema.Comment)
	}
	fmt.Fprintf(b, "type %s struct {\n", name)

	keys := make([]string, 0, len(schema.Properties))
	for k := range schema.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nested bytes.Buffer
	for _, key := range keys {
		sub := schema.Properties[key]
		fieldName := exportName(key)
		goType, err := goType(&nested, name, fieldName, sub, seen, islandName)
		if err != nil {
			return err
		}
		if sub != nil && sub.Comment != "" {
			fmt.Fprintf(b, "\t// %s %s\n", fieldName, sub.Comment)
		}
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", fieldName, goType, key)
	}
	fmt.Fprintf(b, "}\n\n")

	b.Write(nested.Bytes())
	return nil
}

// goType returns the Go type expression for a schema, emitting nested structs
// as needed. parentName and fieldName are used to name nested struct types.
func goType(b *bytes.Buffer, parentName, fieldName string, schema *island.Schema, seen map[string]bool, islandName string) (string, error) {
	if schema == nil {
		return "interface{}", nil
	}
	switch schema.Type {
	case "string":
		return "string", nil
	case "number":
		return "float64", nil
	case "integer":
		return "int", nil
	case "boolean":
		return "bool", nil
	case "array":
		if schema.Items == nil {
			return "[]interface{}", nil
		}
		elem, err := goType(b, parentName, fieldName, schema.Items, seen, islandName)
		if err != nil {
			return "", err
		}
		return "[]" + elem, nil
	case "object":
		nestedName := parentName + fieldName
		if err := emitStruct(b, nestedName, schema, seen, islandName); err != nil {
			return "", err
		}
		return nestedName, nil
	default:
		return "", fmt.Errorf("unsupported schema type %q in island %s", schema.Type, islandName)
	}
}

func emitInjector(b *bytes.Buffer) {
	b.WriteString("// injectIsland writes html to w with the bytes between [open, close)\n")
	b.WriteString("// replaced by blob. The offsets are the data island script body\n")
	b.WriteString("// bounds, computed at codegen time. This is the only runtime\n")
	b.WriteString("// helper in the generated file.\n")
	b.WriteString("func injectIsland(w io.Writer, html []byte, blob []byte, open, close int) error {\n")
	b.WriteString("\tfor _, part := range [][]byte{html[:open], blob, html[close:]} {\n")
	b.WriteString("\t\tif _, err := w.Write(part); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
}

func exportName(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func unexportName(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
