// Package codegen emits one self-contained Go file per directory from parsed
// island files. Per island: a typed Data struct, embedded HTML, and a
// Render<Name> function. Resolved CDN deps are embedded from the vendor
// cache dir and spliced into the output at render time (no intermediate
// baked files). Generated code imports only the standard library.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"unicode"

	"github.com/fritzkeyzer/islandc/internal/island"
	"github.com/fritzkeyzer/islandc/internal/parts"
)

// Config describes one directory's generation input.
type Config struct {
	PackageName string
	Files       []*island.File
	// Version is the islandc version written into the generated header.
	Version string
	// Resolved maps a dep URL to its vendored filename within DepsDir.
	// Islands referencing a resolved URL splice the embedded content in
	// place of the CDN tag at render time. May be nil.
	Resolved map[string]string
	// DepsDir is the vendor cache directory relative to the package dir
	// (e.g. "islandc.deps"). Required when Resolved is non-empty.
	DepsDir string
}

// Generate returns the formatted Go source for one directory's islands.
func Generate(cfg Config) ([]byte, error) {
	if cfg.PackageName == "" {
		return nil, fmt.Errorf("codegen: package name is required")
	}
	if len(cfg.Files) == 0 {
		return nil, fmt.Errorf("codegen: no island files given")
	}

	files := make([]*island.File, len(cfg.Files))
	copy(files, cfg.Files)
	sort.Slice(files, func(i, j int) bool { return files[i].Name < files[j].Name })

	deps, err := collectDeps(cfg, files)
	if err != nil {
		return nil, err
	}

	version := cfg.Version
	if version == "" {
		version = "dev"
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by islandc (%s). DO NOT EDIT.\n\n", version)
	b.WriteString("package " + cfg.PackageName + "\n\n")
	b.WriteString("import (\n")
	if deps.hasJS {
		b.WriteString("\t\"bytes\"\n")
	}
	b.WriteString("\t_ \"embed\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"io\"\n")
	b.WriteString(")\n\n")

	emitDeps(&b, deps)

	seen := map[string]bool{}
	for _, f := range files {
		if err := emitIsland(&b, f, deps.varOf, seen); err != nil {
			return nil, fmt.Errorf("codegen %s: %w", f.Path, err)
		}
	}
	emitWriter(&b)

	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("codegen: generated output does not gofmt: %w\n---\n%s", err, b.String())
	}
	return out, nil
}

// depSet describes the resolved deps referenced by a directory's islands:
// one embedded package-level var per unique URL.
type depSet struct {
	// urls are the referenced resolved URLs, sorted for stable output.
	urls []string
	// varOf maps a URL to its generated variable name (dep0, dep1, ...).
	varOf map[string]string
	// fileOf maps a URL to its vendored filename (CDN: within depsDir;
	// local: the path with leading ./ stripped, embedded from package dir).
	fileOf map[string]string
	// localOf marks URLs whose fileOf is a package-dir-relative path
	// rather than a depsDir cache file.
	localOf map[string]bool
	// kindOf maps a URL to its dep kind.
	kindOf  map[string]island.DepKind
	depsDir string
	hasJS   bool
}

// collectDeps gathers the resolved dep URLs referenced by files and assigns
// stable variable names. Both CDN-resolved deps (cfg.Resolved[URL] = cache
// filename) and local deps (DepRef.Local, embedded from the package dir)
// are included.
func collectDeps(cfg Config, files []*island.File) (*depSet, error) {
	d := &depSet{
		varOf:   map[string]string{},
		fileOf:  map[string]string{},
		localOf: map[string]bool{},
		kindOf:  map[string]island.DepKind{},
		depsDir: cfg.DepsDir,
	}
	hasCDN := false
	for _, f := range files {
		for _, ref := range f.Deps {
			file, ok := cfg.Resolved[ref.URL]
			if !ok {
				continue
			}
			if _, seen := d.fileOf[ref.URL]; seen {
				continue
			}
			d.urls = append(d.urls, ref.URL)
			d.fileOf[ref.URL] = file
			d.kindOf[ref.URL] = ref.Kind
			d.localOf[ref.URL] = ref.Local
			if !ref.Local {
				hasCDN = true
			}
			if ref.Kind == island.DepJS {
				d.hasJS = true
			}
		}
	}
	if hasCDN && cfg.DepsDir == "" {
		return nil, fmt.Errorf("codegen: DepsDir is required when resolved CDN deps are given")
	}
	sort.Strings(d.urls)
	for i, u := range d.urls {
		d.varOf[u] = fmt.Sprintf("dep%d", i)
	}
	return d, nil
}

// emitDeps writes one embedded var per resolved dep. JS content gets
// "</script" escaped to "<\/script" once at package init, so any JS dep can
// be spliced into a <script> element safely. Local deps embed from the
// package dir (no depsDir prefix); CDN deps embed from depsDir.
func emitDeps(b *bytes.Buffer, d *depSet) {
	for _, u := range d.urls {
		v := d.varOf[u]
		var embedPath string
		if d.localOf[u] {
			embedPath = d.fileOf[u]
		} else {
			embedPath = d.depsDir + "/" + d.fileOf[u]
		}
		fmt.Fprintf(b, "// %s is the vendored content of %s.\n", v, u)
		switch d.kindOf[u] {
		case island.DepJS:
			fmt.Fprintf(b, "//go:embed %s\n", embedPath)
			fmt.Fprintf(b, "var %sRaw []byte\n\n", v)
			fmt.Fprintf(b, "var %s = bytes.ReplaceAll(%sRaw, []byte(\"</script\"), []byte(\"<\\\\/script\"))\n\n", v, v)
		default:
			fmt.Fprintf(b, "//go:embed %s\n", embedPath)
			fmt.Fprintf(b, "var %s []byte\n\n", v)
		}
	}
}

// emitIsland writes one island's struct, embedded HTML, and Render function.
func emitIsland(b *bytes.Buffer, f *island.File, depVar map[string]string, seen map[string]bool) error {
	dataName := f.Name + "Data"
	if seen[dataName] {
		return fmt.Errorf("duplicate generated type %q (from %s)", dataName, f.Path)
	}
	if err := emitStruct(b, dataName, f.Schema, seen, f.Name); err != nil {
		return err
	}

	htmlVar := unexportName(f.Name) + "HTML"
	fmt.Fprintf(b, "//go:embed %s\n", f.Path)
	fmt.Fprintf(b, "var %s []byte\n\n", htmlVar)

	fmt.Fprintf(b, "// %s writes the %s island HTML with the data island's object\n", f.RenderFunc, f.Name)
	fmt.Fprintf(b, "// literal replaced by json.Marshal(d).\n")
	fmt.Fprintf(b, "func %s(w io.Writer, d %s) error {\n", f.RenderFunc, dataName)
	fmt.Fprintf(b, "\tblob, err := json.Marshal(d)\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn err\n\t}\n")
	fmt.Fprintf(b, "\treturn writeParts(w,\n")
	for _, expr := range renderParts(f, depVar, htmlVar) {
		fmt.Fprintf(b, "\t\t%s,\n", expr)
	}
	fmt.Fprintf(b, "\t)\n")
	fmt.Fprintf(b, "}\n\n")
	return nil
}

// renderParts computes the ordered part expressions for one island's render
// function: slices of the pristine source HTML interleaved with embedded dep
// content (first occurrence inlined, duplicates dropped, unresolved deps
// verbatim) and the marshaled data blob.
func renderParts(f *island.File, depVar map[string]string, htmlVar string) []string {
	var exprs []string
	for _, p := range parts.Plan(f, depVar) {
		switch {
		case p.Blob:
			exprs = append(exprs, "blob")
		case p.DepURL != "":
			v, ok := depVar[p.DepURL]
			if !ok {
				continue // unresolved: should not happen (Plan only emits resolved deps)
			}
			switch p.Kind {
			case island.DepCSS:
				exprs = append(exprs, `[]byte("<style>")`, v, `[]byte("</style>")`)
			case island.DepJS:
				exprs = append(exprs, fmt.Sprintf("[]byte(%q)", p.ScriptOpenTag), v, `[]byte("</script>")`)
			}
		default:
			if p.Src[1] == len(f.HTML) {
				exprs = append(exprs, fmt.Sprintf("%s[%d:]", htmlVar, p.Src[0]))
			} else {
				exprs = append(exprs, fmt.Sprintf("%s[%d:%d]", htmlVar, p.Src[0], p.Src[1]))
			}
		}
	}
	return exprs
}

// emitStruct writes a Go struct for the given schema node. Nested object
// schemas become nested structs named <Parent><FieldName>, emitted after the
// parent struct.
func emitStruct(b *bytes.Buffer, name string, schema *island.Schema, seen map[string]bool, islandName string) error {
	if schema.Type != "object" {
		return fmt.Errorf("struct %s: schema type is %q, want object", name, schema.Type)
	}
	if seen[name] {
		return fmt.Errorf("duplicate generated type %q", name)
	}
	seen[name] = true

	if schema.Comment != "" {
		fmt.Fprintf(b, "// %s %s\n", name, schema.Comment)
	}
	fmt.Fprintf(b, "type %s struct {\n", name)

	keys := make([]string, 0, len(schema.Properties))
	for k := range schema.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var nested bytes.Buffer
	for _, key := range keys {
		sub := schema.Properties[key]
		fieldName := exportName(key)
		goType, err := goType(&nested, name, fieldName, sub, seen, islandName)
		if err != nil {
			return err
		}
		if sub != nil && sub.Comment != "" {
			fmt.Fprintf(b, "\t// %s %s\n", fieldName, sub.Comment)
		}
		fmt.Fprintf(b, "\t%s %s `json:\"%s\"`\n", fieldName, goType, key)
	}
	fmt.Fprintf(b, "}\n\n")

	b.Write(nested.Bytes())
	return nil
}

// goType returns the Go type expression for a schema, emitting nested structs
// as needed. parentName and fieldName are used to name nested struct types.
func goType(b *bytes.Buffer, parentName, fieldName string, schema *island.Schema, seen map[string]bool, islandName string) (string, error) {
	if schema == nil {
		return "interface{}", nil
	}
	switch schema.Type {
	case "string":
		return "string", nil
	case "number":
		return "float64", nil
	case "integer":
		return "int", nil
	case "boolean":
		return "bool", nil
	case "array":
		if schema.Items == nil {
			return "[]interface{}", nil
		}
		elem, err := goType(b, parentName, fieldName, schema.Items, seen, islandName)
		if err != nil {
			return "", err
		}
		return "[]" + elem, nil
	case "object":
		nestedName := parentName + fieldName
		if err := emitStruct(b, nestedName, schema, seen, islandName); err != nil {
			return "", err
		}
		return nestedName, nil
	default:
		return "", fmt.Errorf("unsupported schema type %q in island %s", schema.Type, islandName)
	}
}

func emitWriter(b *bytes.Buffer) {
	b.WriteString("// writeParts writes each part to w in order: slices of the embedded\n")
	b.WriteString("// island HTML interleaved with vendored dep content and the marshaled\n")
	b.WriteString("// data blob. This is the only runtime helper in the generated file.\n")
	b.WriteString("func writeParts(w io.Writer, parts ...[]byte) error {\n")
	b.WriteString("\tfor _, part := range parts {\n")
	b.WriteString("\t\tif _, err := w.Write(part); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")
}

func exportName(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func unexportName(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}
