// Code generated by islandc (v0.1.1). DO NOT EDIT.

package testdata

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"io"
)

// dep0 is the vendored content of https://cdn.jsdelivr.net/npm/alpinejs@3.14.1/dist/cdn.min.js.
//
//go:embed islandc.deps/c213894838ada545785d06464ddfbf2cb1612b4594bad8a1d4ac71e1a2feda6a.js
var dep0Raw []byte

var dep0 = bytes.ReplaceAll(dep0Raw, []byte("</script"), []byte("<\\/script"))

// dep1 is the vendored content of https://cdn.jsdelivr.net/npm/open-props@1.7.0/open-props.min.css.
//
//go:embed islandc.deps/860f1c4a7d44015e949f65aee04ac2b8fce63cf0fa898209609f23297dc03989.css
var dep1 []byte

type ColorPickerData struct {
	// H hue 0..360
	H int `json:"h"`
	// L lightness 0..100
	L       int                      `json:"l"`
	Presets []ColorPickerDataPresets `json:"presets"`
	// S saturation 0..100
	S int `json:"s"`
}

type ColorPickerDataPresets struct {
	H    int    `json:"h"`
	L    int    `json:"l"`
	Name string `json:"name"`
	S    int    `json:"s"`
}

//go:embed color_picker.island.html
var colorPickerHTML []byte

// RenderColorPicker writes the ColorPicker island HTML with the data island's object
// literal replaced by json.Marshal(d).
func RenderColorPicker(w io.Writer, d ColorPickerData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return writeParts(w,
		colorPickerHTML[0:173],
		[]byte("<style>"),
		dep1,
		[]byte("</style>"),
		colorPickerHTML[278:4371],
		blob,
		colorPickerHTML[4763:5890],
		[]byte("<script defer>"),
		dep0,
		[]byte("</script>"),
		colorPickerHTML[5988:],
	)
}

type CounterData struct {
	// Count current click count
	Count int    `json:"count"`
	Label string `json:"label"`
	Max   int    `json:"max"`
	Min   int    `json:"min"`
	// Step amount added/removed per click
	Step int `json:"step"`
}

//go:embed counter.island.html
var counterHTML []byte

// RenderCounter writes the Counter island HTML with the data island's object
// literal replaced by json.Marshal(d).
func RenderCounter(w io.Writer, d CounterData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return writeParts(w,
		counterHTML[0:2117],
		blob,
		counterHTML[2264:],
	)
}

type LiveClockData struct {
	// Hour24 24-hour format when true
	Hour24 bool `json:"hour24"`
	// TickHz refresh frequency in Hz
	TickHz int `json:"tickHz"`
	// Timezone IANA tz name, or "local"
	Timezone string `json:"timezone"`
}

//go:embed live_clock.island.html
var liveClockHTML []byte

// RenderLiveClock writes the LiveClock island HTML with the data island's object
// literal replaced by json.Marshal(d).
func RenderLiveClock(w io.Writer, d LiveClockData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return writeParts(w,
		liveClockHTML[0:1758],
		blob,
		liveClockHTML[1907:],
	)
}

type ProfileData struct {
	Avatar string             `json:"avatar"`
	Name   string             `json:"name"`
	Role   string             `json:"role"`
	Stats  []ProfileDataStats `json:"stats"`
}

type ProfileDataStats struct {
	Label string  `json:"label"`
	Value float64 `json:"value"`
}

//go:embed profile.island.html
var profileHTML []byte

// RenderProfile writes the Profile island HTML with the data island's object
// literal replaced by json.Marshal(d).
func RenderProfile(w io.Writer, d ProfileData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return writeParts(w,
		profileHTML[0:4198],
		blob,
		profileHTML[4490:],
	)
}

type TodoListData struct {
	Items []TodoListDataItems `json:"items"`
	Title string              `json:"title"`
}

type TodoListDataItems struct {
	Done bool   `json:"done"`
	Text string `json:"text"`
}

//go:embed todo_list.island.html
var todoListHTML []byte

// RenderTodoList writes the TodoList island HTML with the data island's object
// literal replaced by json.Marshal(d).
func RenderTodoList(w io.Writer, d TodoListData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return writeParts(w,
		todoListHTML[0:3327],
		blob,
		todoListHTML[3509:],
	)
}

// writeParts writes each part to w in order: slices of the embedded
// island HTML interleaved with vendored dep content and the marshaled
// data blob. This is the only runtime helper in the generated file.
func writeParts(w io.Writer, parts ...[]byte) error {
	for _, part := range parts {
		if _, err := w.Write(part); err != nil {
			return err
		}
	}
	return nil
}
