// Code generated by islandc (v0.1.0). DO NOT EDIT.

package testdata

import (
	_ "embed"
	"encoding/json"
	"io"
)

type ColorPickerData struct {
	// H hue 0..360
	H int `json:"h"`
	// L lightness 0..100
	L       int                      `json:"l"`
	Presets []ColorPickerDataPresets `json:"presets"`
	// S saturation 0..100
	S int `json:"s"`
}

type ColorPickerDataPresets struct {
	H    int    `json:"h"`
	L    int    `json:"l"`
	Name string `json:"name"`
	S    int    `json:"s"`
}

//go:embed color_picker.island.gen.html
var colorPickerHTML []byte

// RenderColorPicker writes the ColorPicker island HTML with the data island body
// replaced by json.Marshal(d).
func RenderColorPicker(w io.Writer, d ColorPickerData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, colorPickerHTML, blob, 72069, 72468)
}

type CounterData struct {
	// Count current click count
	Count int    `json:"count"`
	Label string `json:"label"`
	Max   int    `json:"max"`
	Min   int    `json:"min"`
	// Step amount added/removed per click
	Step int `json:"step"`
}

//go:embed counter.island.html
var counterHTML []byte

// RenderCounter writes the Counter island HTML with the data island body
// replaced by json.Marshal(d).
func RenderCounter(w io.Writer, d CounterData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, counterHTML, blob, 2019, 2173)
}

type LiveClockData struct {
	// Hour24 24-hour format when true
	Hour24 bool `json:"hour24"`
	// TickHz refresh frequency in Hz
	TickHz int `json:"tickHz"`
	// Timezone IANA tz name, or "local"
	Timezone string `json:"timezone"`
}

//go:embed live_clock.island.html
var liveClockHTML []byte

// RenderLiveClock writes the LiveClock island HTML with the data island body
// replaced by json.Marshal(d).
func RenderLiveClock(w io.Writer, d LiveClockData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, liveClockHTML, blob, 1726, 1882)
}

type ProfileData struct {
	Avatar string             `json:"avatar"`
	Name   string             `json:"name"`
	Role   string             `json:"role"`
	Stats  []ProfileDataStats `json:"stats"`
}

type ProfileDataStats struct {
	Label string  `json:"label"`
	Value float64 `json:"value"`
}

//go:embed profile.island.html
var profileHTML []byte

// RenderProfile writes the Profile island HTML with the data island body
// replaced by json.Marshal(d).
func RenderProfile(w io.Writer, d ProfileData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, profileHTML, blob, 4173, 4472)
}

type TodoListData struct {
	Items []TodoListDataItems `json:"items"`
	Title string              `json:"title"`
}

type TodoListDataItems struct {
	Done bool   `json:"done"`
	Text string `json:"text"`
}

//go:embed todo_list.island.html
var todoListHTML []byte

// RenderTodoList writes the TodoList island HTML with the data island body
// replaced by json.Marshal(d).
func RenderTodoList(w io.Writer, d TodoListData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, todoListHTML, blob, 3295, 3484)
}

// injectIsland writes html to w with the bytes between [open, close)
// replaced by blob. The offsets are the data island script body
// bounds, computed at codegen time. This is the only runtime
// helper in the generated file.
func injectIsland(w io.Writer, html []byte, blob []byte, open, close int) error {
	for _, part := range [][]byte{html[:open], blob, html[close:]} {
		if _, err := w.Write(part); err != nil {
			return err
		}
	}
	return nil
}
