// Code generated by islandc. DO NOT EDIT.
//
// Source: .island.html files in this directory. See https://github.com/fritzkeyzer/islandc for the format.
//
// Each Render<Name> function writes the source HTML verbatim with the
// island-data placeholder JSON replaced by json.Marshal(data).

package testdata

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"io"
)

type ColorPickerData struct {
	H       int                      `json:"h"`
	L       int                      `json:"l"`
	Presets []ColorPickerDataPresets `json:"presets"`
	S       int                      `json:"s"`
}

type ColorPickerDataPresets struct {
	H    int    `json:"h"`
	L    int    `json:"l"`
	Name string `json:"name"`
	S    int    `json:"s"`
}

// colorPickerHTML is the source file verbatim, including the placeholder
// JSON inside the island-data slot. injectIsland overwrites that
// placeholder at serve time.
//
//go:embed color_picker.island.html
var colorPickerHTML []byte

// RenderColorPicker writes the ColorPicker island HTML to w with the island-data
// placeholder replaced by the marshaled form of d.
func RenderColorPicker(w io.Writer, d ColorPickerData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, colorPickerHTML, blob, 3523, 3867)
}

type CounterData struct {
	Count int    `json:"count"`
	Label string `json:"label"`
	Max   int    `json:"max"`
	Min   int    `json:"min"`
	Step  int    `json:"step"`
}

// counterHTML is the source file verbatim, including the placeholder
// JSON inside the island-data slot. injectIsland overwrites that
// placeholder at serve time.
//
//go:embed counter.island.html
var counterHTML []byte

// RenderCounter writes the Counter island HTML to w with the island-data
// placeholder replaced by the marshaled form of d.
func RenderCounter(w io.Writer, d CounterData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, counterHTML, blob, 2399, 2496)
}

type LiveClockData struct {
	Hour24   bool    `json:"hour24"`
	TickHz   float64 `json:"tickHz"`
	Timezone string  `json:"timezone"`
}

// liveClockHTML is the source file verbatim, including the placeholder
// JSON inside the island-data slot. injectIsland overwrites that
// placeholder at serve time.
//
//go:embed live_clock.island.html
var liveClockHTML []byte

// RenderLiveClock writes the LiveClock island HTML to w with the island-data
// placeholder replaced by the marshaled form of d.
func RenderLiveClock(w io.Writer, d LiveClockData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, liveClockHTML, blob, 2000, 2072)
}

type ProfileData struct {
	Avatar string             `json:"avatar"`
	Name   string             `json:"name"`
	Role   string             `json:"role"`
	Stats  []ProfileDataStats `json:"stats"`
}

type ProfileDataStats struct {
	Label string  `json:"label"`
	Value float64 `json:"value"`
}

// profileHTML is the source file verbatim, including the placeholder
// JSON inside the island-data slot. injectIsland overwrites that
// placeholder at serve time.
//
//go:embed profile.island.html
var profileHTML []byte

// RenderProfile writes the Profile island HTML to w with the island-data
// placeholder replaced by the marshaled form of d.
func RenderProfile(w io.Writer, d ProfileData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, profileHTML, blob, 4721, 5020)
}

type TodoListData struct {
	Items []TodoListDataItems `json:"items"`
	Title string              `json:"title"`
}

type TodoListDataItems struct {
	Done bool   `json:"done"`
	Text string `json:"text"`
}

// todoListHTML is the source file verbatim, including the placeholder
// JSON inside the island-data slot. injectIsland overwrites that
// placeholder at serve time.
//
//go:embed todo_list.island.html
var todoListHTML []byte

// RenderTodoList writes the TodoList island HTML to w with the island-data
// placeholder replaced by the marshaled form of d.
func RenderTodoList(w io.Writer, d TodoListData) error {
	blob, err := json.Marshal(d)
	if err != nil {
		return err
	}
	return injectIsland(w, todoListHTML, blob, 3732, 3921)
}

// injectIsland writes html to w with the bytes between
// [openEnd, closeStart) replaced by blob. openEnd and closeStart
// are the absolute byte offsets of the island-data slot's opening
// tag end and closing tag start, computed at codegen time.
func injectIsland(w io.Writer, html, blob []byte, openEnd, closeStart int) error {
	if openEnd < 0 || closeStart < 0 || openEnd > closeStart || closeStart > len(html) {
		return fmt.Errorf("islandc: invalid island-data splice bounds")
	}
	if _, err := w.Write(html[:openEnd]); err != nil {
		return err
	}
	if _, err := w.Write(blob); err != nil {
		return err
	}
	_, err := w.Write(html[closeStart:])
	return err
}
